### ISSUE TITLE
Continue to improve the pre-publish checklist

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#581]
- [ ] Add space between points in the checklist
- [ ] Detect "News" category by inspecting the category rather than checking for the external url
- [ ] For "News" posts, check to make sure the external url is filled in
- [ ] Find a way to make the checklist update when the "Publish" button is pressed
- [ ] When you set a date for the webinar, there are no longer any items that show in the pre-publish checklist, however, the header for the list still shows in the sidebar. Either we should hide the header when there are no items or leave the "webinar date" item in the list and mark it as "done", as you've done with other items

**Comment by cjyabraham** [comment]
Sorry, posted this in the wrong repo.
