### ISSUE TITLE
Improve and standardize event-specific tracking

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#587]
- [ ] Standardize the way we track analytics and event registrations in GTM and Cvent.
- [ ] There are a 28 different code snippets in Cvent.  Figure out which ones are in use and which can be cleaned out.
- [x] Create folders in GTM for each event etc.
- [ ] Document the solution

**Comment by cjyabraham** [comment]
Closing this for now as no longer needed
